# Generated by Django 3.1.4 on 2021-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('problem', models.TextField()),
            ],
        ),
    ]
