# Generated by Django 3.1.4 on 2021-01-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
