# Generated by Django 3.1.4 on 2021-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210120_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
