# Generated by Django 3.1.4 on 2021-02-17 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210216_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('problem', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
