# Generated by Django 3.1.4 on 2021-02-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210217_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings1',
            name='service',
            field=models.CharField(max_length=150),
        ),
    ]
