# Generated by Django 3.1.4 on 2021-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210217_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=150)),
                ('suits', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
