# Generated by Django 3.1.4 on 2021-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='img',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='paint'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='rating',
            field=models.FloatField(),
        ),
    ]
