# Generated by Django 3.1.4 on 2021-03-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_services_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings1',
            name='problem',
        ),
    ]
