# Generated by Django 3.1.4 on 2021-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_bookings1_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings1',
            name='state',
            field=models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('Telangana', 'Telangana'), ('Maharastra', 'Maharastra')], max_length=150),
        ),
    ]
