# Generated by Django 3.1.4 on 2021-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210502_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='minimum_charges',
            field=models.FloatField(default=0.0),
        ),
    ]
