# Generated by Django 3.1.4 on 2021-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_services_minimum_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpentering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('lock', models.CharField(max_length=250)),
                ('hinges', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
