# Generated by Django 3.1.4 on 2021-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_carpentering'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpentering',
            name='img',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='carpenter'),
        ),
    ]
