# Generated by Django 3.1.4 on 2021-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='employee_count',
            field=models.IntegerField(default=1),
        ),
    ]
